# Vagrant file to launch single instance
# with puppet run after startup
#
# Author: Thomas Bendler <project@bendler-net.de>
# Date:   Tue Jun  3 14:30:33 CEST 2014
#

### Specify the API version that should be used ###
VAGRANTFILE_API_VERSION = "2"

### Parameter for box settings ###
box      = 'thbe-centos6x'
hostname = 'vagrant-centos6x-v2'
domain   = 'thbe.local'
ip       = '10.0.2.15'
ram      = '2048'
cpu      = '2'
group    = '/Vagrant'

### Vagrant configuration for startup the virtual machine ###
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = box
  config.vm.host_name = hostname + '.' + domain
  config.vm.network "private_network", ip: ip
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

  config.vm.provider :virtualbox do |v, override|
    override.vm.box = "puppetlabs/centos-6.6-64-puppet"
    v.customize [
      'modifyvm', :id,
      '--groups', "/Vagrant",
      '--cpus', cpu,
      '--name', hostname,
      '--memory', ram
    ]
  end

  config.vm.provider :parallels do |p, override|
    override.vm.box = "parallels/centos-6.6"
    p.name = "CentOS 6x Vagrant"
    p.update_guest_tools = false
    p.optimize_power_consumption = false
    p.memory = ram
    p.cpus = cpu
  end

  config.ssh.forward_agent = true
  config.ssh.pty = true

  config.vm.provision "shell", inline: "/bin/sh /vagrant/script/puppet.sh clean"
end
