# Vagrant file to launch single instance
# with puppet run after startup
#
# Author: Thomas Bendler <project@bendler-net.de>
# Date:   Wed Jun  4 21:53:17 CEST 2014
#

### Specify the API version that should be used ###
VAGRANTFILE_API_VERSION = "2"

### Parameter for box settings ###
box      = 'macosx'
url      = 'https://vagrantcloud.com/AndrewDryga/osx-mavericks/version/2/provider/virtualbox.box'
hostname = 'vagrant-macosx-1'
domain   = 'thbe.local'
ip       = '192.168.14.14'
ram      = '2048'
cpu      = '2'
group    = '/Vagrant'

### Vagrant configuration for startup the virtual machine ###
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = box
  config.vm.box_url = url
  config.vm.host_name = hostname + '.' + domain
  config.vm.network "private_network", ip: ip

  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      'modifyvm', :id,
      '--groups', group,
      '--cpus', cpu,
      '--name', hostname,
      '--memory', ram
    ]
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.manifest_file = 'site.pp'
    puppet.module_path = 'puppet/modules'
  end

  config.ssh.forward_agent = true
end
