# Vagrant file to launch single instance
# with puppet run after startup
#
# Author: Thomas Bendler <project@bendler-net.de>
# Date:   Tue Jun  3 14:30:33 CEST 2014
#

### Specify the API version that should be used ###
VAGRANTFILE_API_VERSION = "2"

### Parameter for box settings ###
box      = 'parallels/boot2docker'
hostname = 'vagrant-boot2docker-v1'
domain   = 'thbe.local'
ip       = '10.0.2.15'
ram      = '4096'
cpu      = '4'
group    = '/Vagrant'

### Vagrant configuration for startup the virtual machine ###
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = box
  config.vm.host_name = hostname + '.' + domain
  config.vm.network "private_network", ip: ip

  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      'modifyvm', :id,
      '--groups', "/Vagrant",
      '--cpus', cpu,
      '--name', hostname,
      '--memory', ram
    ]
  end

  config.ssh.forward_agent = true
  config.ssh.pty = true
end
